name: Secret Scanning

on:
  workflow_dispatch

jobs:
  job:
    name: secret_scanning
    runs-on: Ubuntu-latest
    steps:

    -  name: Checkout
       uses: actions/checkout@v4.1.5
         
    -  name: Secret Scanning
       uses: aquasecurity/trivy-action@0.19.0
      
