name: Secret Scanning

on:
  workflow_dispatch

jobs:
  job:
    name: secret_scanning
    runs-on: Ubuntu-latest
    steps:

      name: Secret Scanning
      uses: aquasecurity/trivy-action@0.19.0
      
