name: SimpleWorkflow
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
       - uses: actions/checkout@v4.1.7

