name: Output Something
on:
  workflow_dispatch

jobs:
  job:
    runs-on: ubuntu-latest
    
    steps:
      -  name: Checkout
         uses: actions/checkout@v4.1.5


      - id: set-value
        name: Generate a value
        run: |
          value="test"
          echo "new-key=$value" >> "$GITHUB_OUTPUT"

      - name: Access it
        run: |
          echo "the secret number is ${{ steps.sets-value.outputs.new-key }}"
          
  
