name: Output Something
on:
  workflow_dispatch

jobs:
  job:
    runs-on: ubuntu-latest
    
    steps:
      -  name: Checkout
         uses: actions/checkout@v4.1.5

      -  name: Execute Command
         run: echo "REPORT_DATE=$(TZ=':Asia/Kolkata' date '+%Y-%m-%d %T')" >> $GITHUB_OUTPUT

      -  name:  Display Date
         run: echo "$GITHUB_OUTPUT"
      


          
  
