name: 11.Workflows-SimpleExpressions

on:
  workflow_dispatch

env:
  TestExpression1: "Expression1"
  TestExpression2: Expression2
  TestExpression3: Expression3

jobs:
  SimpleExpressions1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Expression1
        run: echo ${{ env.TestExpression1 }}

      - name: Print Expression2
        run: echo $TestExpression2

      - name: Print Expression3
        run: echo TESTEXPRESSION3


  SimpleExpressions2:
    runs-on: ubuntu-latest
    env:
      NullExp1: ${{ null }}
      BooleanExpTrue: $${{ true }}
      BooleanExpFalse: $${ false }}
      IntegerExp: ${{ 521 }}
      FloatExp: ${{ 5.21 }}
      HexExp: ${{ 0xffdd }}
      ExponentialExp: ${{ 2.e-2 }}
      StringExp: ${{ catkitten }}
      StringBracesExp: ${{ "Cat is a good kitten" }}
      
    steps:
      - name: Print Null Expression
        run: echo ${{ env.NullExp1 }}
        
      - name: Print Boolean True
        run: echo ${{ env.BooleanExpTrue }}

      - name: Print Boolean False
        run: echo ${{ env.BooleanExpFalse }}

      - name: Print Integer Expression
        run: echo ${{ env.IntegerExp }}

      - name: Print Float Expression
        run: echo ${{ env.FloatExp }}

      - name: Print Hex Expression
        run: echo ${{ env.HexExp }}

      - name: Print Expontential Expression
        run: echo ${{ env.ExponentialExp }}

      - name: Print String Expression
        run: echo ${{ env.StringExp }}

      - name: Print String BracesExpression
        run: echo ${{ env.StringBracesExp }}
