name: 11.Workflows-SimpleExpressions

on:
  workflow_dispatch

env:
  TestExpression1: "Expression1"
  TestExpression2: Expression2

jobs:
  SimpleExpressions1:
    runs-on: ubuntu-latest
    steps:
      - name: Expression1
        run: echo ${{ env.TestExpression1 }}

      - name: Expression2
        run: echo $TestExpression2
