name: 12a.Workflows-SimpleContexts

on: workflow_dispatch

jobs:
 SimpleContexts1:
   runs-on: ubuntu-latest

   steps:
     - name: Print Hello
       run: echo "Hello"

 GitHubAllContext:
    runs-on: ubuntu-latest

    steps:
     - name: GitHub Contexts
       env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
       run: echo "$GITHUB_CONTEXT"

 GitHubContextIndividual:
    runs-on: windows-latest

    steps:
      - name: GitHub Contexts
        env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: GitHubJob
        run: echo ${{github.job}}

      - name: GitHubSHA
        run: echo ${{github.sha}}    
