name: 12a.Workflows-SimpleContexts

on: workflow_dispatch

jobs:
 SimpleContexts1:
   runs-on: ubuntu-latest

   steps:
     - name: Print Hello
       run: echo "Hello"

 GitHubContext:
    runs-on: ubuntu-latest

    steps:
     - name: GitHub Contexts
       run: |
        echo github.action
        echo github.action_path
