name: 12b.Workflows-JobContexts

on: workflow_dispatch

jobs:
 SimpleContexts1:
   runs-on: ubuntu-latest

   steps:
     - name: Print Hello
       run: echo "Hello"

 GitHubAllContext:
    runs-on: ubuntu-latest

    steps:
     - name: GitHub Contexts
       env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
       run: echo "$GITHUB_CONTEXT"       

     - name: Job Contexts
       env:
          JOBS_CONTEXT: ${{ toJson(job) }}
       run: echo "$JOBS_CONTEXT"


   
