name: 12c.Workflows-ComplexContexts.yml

on: 
  workflow_dispatch:
    inputs:
      variable_check:
        required: true
        type: string
      variable1_check:
        required: true
        type: string
      variable2_check:
        required: true
        type: string
      perform_deploy:
        required: true
        type: boolean

  
jobs:
  InputContextsBoolean-Job:
    runs-on: ubuntu-20.04
    if: ${{ inputs.perform_deploy }}
    steps:
     - name: Print Hello
       run: echo "Input Context Boolean Check"
       
  InputContextsVariable-Check:
    runs-on: ubuntu-20.04
    if: ${{ inputs.variable_check == 'true' }}
    steps:
     - name: Print Hello
       run: echo "Input Variable Check"
       
     - name: Print the Variable
       run: echo ${{ inputs.variable_check }}

  InputContexts2Variables-Check:
    runs-on: ubuntu-latest
    if: ${{ inputs.variable1_check == 'true' && inputs.variable2_check == 'true' }}
    steps:
     - name: Print Hello
       run: echo "Input Variable Check"
       
     - name: Print the Variable
       run: echo ${{ inputs.variable2_check }}
