name: 12c.Workflows-ComplexContexts.yml

on: 
  workflow_dispatch:
    inputs:
          variable_check:
            required: true
            type: string
          deploy_target:
            required: true
            type: string
          perform_deploy:
            required: true
            type: boolean

  
jobs:
  InputContextsBoolean-Job:
    runs-on: ubuntu-latest
    if: ${{ inputs.perform_deploy }}
    steps:
     - name: Print Hello
       run: echo "Input Context Boolean Check"
       
  InputContextsVariable-Check:
    runs-on: ubuntu-latest
    if: ${{ inputs.variable_check == "true" }}
    steps:
     - name: Print Hello
       run: echo "Input Variable Check"
       
     - name: Print the Variable
       run: echo ${{ inputs.variable_check }}
