
name: 21.TestPythonArgs

on:
  workflow_dispatch

env:
  test1: Test1
  test2: Test2
  
jobs:
  PythonTest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Scripts/Python
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:      
          repository: ${{ github.repository }}


      - name: Python Passing arguments
        run: python test1.py ${test1} ${test2}
            
