
name: 21.TestPythonArgs

on:
  workflow_dispatch
  
jobs:
  PythonTest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Scripts/Python
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:      
          repository: ${{ github.repository }}


      - name: Python Passing arguments
        run: python test1.py "Shan" "Ganesh"
            
