name: 3.SimpleBashShell-WithScript

on:
  workflow_dispatch
  
jobs:
  job:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:      
          repository: ${{ github.repository }}


      - name: Shell Execution
        run: "echo Shan"

      - name: Make the script files executable
        run: chmod +x /Scripts/Shell/test.sh

      - name: Shell Execution
        run: ./Scripts/Shell/test.sh
            
