name: 3.SimpleBashShell-WithScript

on:
  workflow_dispatch
  
jobs:
  job:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:      
          repository: ${{ github.repository }}


      - name: Shell Execution
        run: "echo Shan"

      - name: current directory
        run: 
           pwd
           dir
           cd Scripts
           cd Shell

      - name: listing directory
        run: dir

      - name: Shell Execution
        run: ./home/runner/work/GitHubActions/GitHubActions/Scripts/Shell/test.sh
            
