name: 8.Workflows-Variables

on:
  workflow_dispatch

jobs:
    GitHub-ActionVariables:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./Scripts/Shell
            
        steps:      
          - name: Checkout
            uses: actions/checkout@v4.1.7
            with:      
              repository: ${{ github.repository }} 

          - name: 1.GitHub Action
            run: echo $GITHUB_ACTION

          - name: 2.GitHub Action Path
            run: echo ${{GITHUB_ACTION_PATH}}

          - name: 3.GITHUB_ACTION_REPOSITORY
            run: echo $GITHUB_ACTION_REPOSITORY

          - name: Workflow Run url
            run: echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
