name: 8.Workflows-Variables

on:
  workflow_dispatch

jobs:
    job1:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./Scripts/Shell
            
        steps:      
          - name: Checkout
            uses: actions/checkout@v4.1.7
            with:      
              repository: ${{ github.repository }} 

          - name: Print GitHub Default variables
            run: echo ${GITHUB_SERVER_URL}

          - name: GitHub Repository
            run: echo ${GITHUB_REPOSITORY}

          - name: Workflow Run url
            run: echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
