name: 8.Workflows-DefaultVariables

on:
  workflow_dispatch

jobs:
    GitHub-ActionVariables:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./Scripts/Shell
            
        steps:      
          - name: Checkout
            uses: actions/checkout@v4.1.7
            with:      
              repository: ${{ github.repository }} 

          - name: 1.GitHub Action
            run: echo $GITHUB_ACTION

          - name: 2.GitHub Action Path
            run: echo $GITHUB_ACTION_PATH

          - name: 3.GitHub Action Repository
            run: echo $GITHUB_ACTION_REPOSITORY

          - name: 4.GitHub Actions
            run : echo $GITHUB_ACTIONS

          - name: 5.GITHUB_ACTOR
            run : echo $GITHUB_ACTOR

          - name: 6.GITHUB_ACTOR_ID
            run: echo $GITHUB_ACTOR_ID

          - name: 7.GITHUB_API_URL
            run: echo $GITHUB_API_URL

          - name: 8.GITHUB_BASE_REF
            run: echo $GITHUB_BASE_REF

          - name: 9.GITHUB_ENV
            run: echo $GITHUB_ENV

          - name: 10.GITHUB_EVENT_NAME
            run: echo $GITHUB_EVENT_NAME

          - name: 11.GITHUB_EVENT_PATH
            run: echo $GITHUB_EVENT_PATH

          - name: 12.GITHUB_GRAPHQL_URL
            run: echo $GITHUB_GRAPHQL_URL
          
          - name: Workflow Run url
            run: echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

    GitHub-RepoVariables:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./Scripts/Shell
            
        steps:
          
            - name: Checkout
              uses: actions/checkout@v4.1.7
              with:      
                repository: ${{ github.repository }} 
                
            - name: 13a.GITHUB_HEAD_REF
              run: echo $GITHUB_HEAD_REF

            - name: 14.GITHUB_JOB
              run: echo $GITHUB_JOB

            - name: 15.GITHUB_OUTPUT
              run: echo $GITHUB_OUTPUT

            - name: 16.GITHUB_PATH
              run: echo $GITHUB_PATH

            - name: 17.GITHUB_REF
              run: echo $GITHUB_REF

            - name: 18.GITHUB_REF_NAME
              run: echo $GITHUB_REF_NAME

            - name: 19.GITHUB_REF_PROTECTED
              run: echo $GITHUB_REF_PROTECTED

            - name: 20.GITHUB_REF_TYPE
              run: echo $GITHUB_REF_TYPE

            - name: 21.GITHUB_REPOSITORY
              run: echo $GITHUB_REPOSITORY

            - name: 22.GITHUB_REPOSITORY_ID
              run: echo $GITHUB_REPOSITORY_ID

            - name: 23.GITHUB_REPOSITORY_OWNER
              run: echo $GITHUB_REPOSITORY_OWNER

            - name: 24.GITHUB_REPOSITORY_OWNER_ID
              run: echo $GITHUB_REPOSITORY_OWNER_ID

    GitHub-RunnerVariables:
        runs-on: ubuntu-latest
        steps:
          - name: 25.GITHUB_RETENTION_DAYS
            run: echo $GITHUB_RETENTION_DAYS

          - name: 26.GITHUB_RUN_ATTEMPT
            run: echo $GITHUB_RUN_ATTEMPT

          - name: 27.GITHUB_RUN_ID
            run: echo $GITHUB_RUN_ID
            
          - name: 28.GITHUB_RUN_NUMBER
            run: echo $GITHUB_RUN_NUMBER

          - name: 29.GITHUB_SERVER_URL
            run: echo $GITHUB_SERVER_URL   
 
          - name: 30.GITHUB_SHA
            run: echo $GITHUB_SHA

          - name: 31.GITHUB_STEP_SUMMARY
            run: echo $GITHUB_STEP_SUMMARY   

          - name: 32.GITHUB_TRIGERRING_ACTOR
            run: echo $GITHUB_TRIGERRING_ACTOR

          - name: 33.GITHUB_WORKFLOW
            run: echo $GITHUB_WORKFLOW      

          - name: 34.GITHUB_WORKFLOW_SHA
            run: echo $GITHUB_WORKFLOW_SHA     

          - name: 35.GITHUB_WORKSPACE
            run: echo $GITHUB_WORKSPACE    
