name: 9.Workflows-CustomVariables

on:
   workflow_dispatch

env:
  Test: Shan
  Test1: Shan1
  Test2: Shan2
  TestExpression: ${{ if test1==test2; true }}

jobs:
   CustomVariables1:      
      runs-on: ubuntu-latest
      steps:
         - name: Test Variable
           run: echo $Test
   
         - name: Test Expression
           run: echo $TestExpression
