name: 9.Workflows-CustomVariables

on:
   workflow_dispatch

env:
  a1: Shan

jobs:
  CustomVariables1:
      
      runs-on: ubuntu-latest
    
      steps:
         - name: Test
           run: echo $a1;
