name: 9.Workflows-CustomVariables

on:
   workflow_dispatch

env:
  Test: Shan
  Test1: Shan1
  Test2: Shan2
  Test3: Shan3
  TestOrgVar1: ${{ var.TEST1 }}
  TestOrgVar2: ${{ var.TEST2 }}
  TestOrgVar3: ${{ var.TEST3 }}
  
jobs:
   CustomVariables1:      
      runs-on: ubuntu-latest
      steps:
         - name: Test Variable
           run: echo $Test
   
         - name: Test Expression
           run: echo ${{ env.Test1 == env.Test2 && true || false }}

         - name: Print Test1
           run: echo ${{ env.Test1 }}
           
         - name: Print Test2
           run: echo ${{ env.Test2 }}

         - name: Print Test3
           run: echo $TEST3

         - name: Print OrgVariable1
           run: echo ${{ env.TestOrgVar1 }}
           
         - name: Print OrgVariable2
           run: echo ${{ env.TestOrgVar2 }}

         - name: Print OrgVariable3
           run: echo ${{ env.TestOrgVar3 }}
