name: Secret Scanning

on:
  workflow_dispatch

jobs:
  job:

    -  name: Checkout
       uses: actions/checkout@v4.1.5
       
    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@0.19.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: 'CRITICAL'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
    
